# Copyright 2024 The AuthRequestAgent Authors.  All rights reserved.
# Use of this source code is governed by an Apache2
# license that can be found in the LICENSE file.

FROM alpine:3.20 

WORKDIR /authz-agent

ARG TARGETOS
ARG TARGETARCH

COPY dist/agent_${TARGETOS}_${TARGETARCH} /authz-agent/agent

ENV PATH=${PATH}:/authz-agent

ENTRYPOINT ["agent"]