# Copyright 2024 The AuthPolicyController Authors.  All rights reserved.
# Use of this source code is governed by an Apache2
# license that can be found in the LICENSE file.

FROM alpine:3.20 

WORKDIR /apc

ARG TARGETOS
ARG TARGETARCH

COPY dist/agent_${TARGETOS}_${TARGETARCH} /apc/agent

ENV PATH=${PATH}:/apc

ENTRYPOINT ["agent"]