// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: api/discovery.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DicsoveryService_Policy_FullMethodName = "/authlink.DicsoveryService/Policy"
)

// DicsoveryServiceClient is the client API for DicsoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DicsoveryServiceClient interface {
	Policy(ctx context.Context, in *GetPolicy, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicySnapshot], error)
}

type dicsoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDicsoveryServiceClient(cc grpc.ClientConnInterface) DicsoveryServiceClient {
	return &dicsoveryServiceClient{cc}
}

func (c *dicsoveryServiceClient) Policy(ctx context.Context, in *GetPolicy, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicySnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DicsoveryService_ServiceDesc.Streams[0], DicsoveryService_Policy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPolicy, PolicySnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DicsoveryService_PolicyClient = grpc.ServerStreamingClient[PolicySnapshot]

// DicsoveryServiceServer is the server API for DicsoveryService service.
// All implementations must embed UnimplementedDicsoveryServiceServer
// for forward compatibility.
type DicsoveryServiceServer interface {
	Policy(*GetPolicy, grpc.ServerStreamingServer[PolicySnapshot]) error
	mustEmbedUnimplementedDicsoveryServiceServer()
}

// UnimplementedDicsoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDicsoveryServiceServer struct{}

func (UnimplementedDicsoveryServiceServer) Policy(*GetPolicy, grpc.ServerStreamingServer[PolicySnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method Policy not implemented")
}
func (UnimplementedDicsoveryServiceServer) mustEmbedUnimplementedDicsoveryServiceServer() {}
func (UnimplementedDicsoveryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDicsoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DicsoveryServiceServer will
// result in compilation errors.
type UnsafeDicsoveryServiceServer interface {
	mustEmbedUnimplementedDicsoveryServiceServer()
}

func RegisterDicsoveryServiceServer(s grpc.ServiceRegistrar, srv DicsoveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDicsoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DicsoveryService_ServiceDesc, srv)
}

func _DicsoveryService_Policy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPolicy)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DicsoveryServiceServer).Policy(m, &grpc.GenericServerStream[GetPolicy, PolicySnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DicsoveryService_PolicyServer = grpc.ServerStreamingServer[PolicySnapshot]

// DicsoveryService_ServiceDesc is the grpc.ServiceDesc for DicsoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DicsoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authlink.DicsoveryService",
	HandlerType: (*DicsoveryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Policy",
			Handler:       _DicsoveryService_Policy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/discovery.proto",
}
